name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.x"

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn run lint

      - name: Build app
        run: yarn run build
